sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY="2.6.*"
services:
  - elasticsearch
before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=vendor/ongr/ongr-strict-standard/Ongr --ignore=vendor/,Tests/app/,Resources/public/ ./
