sudo: required
language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
services:
  - elasticsearch
before_script:
  - if [[ $TRAVIS_PHP_VERSION != "7.0" ]]; then phpenv config-rm xdebug.ini; fi
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - whereis composer
  - php -dmemory_limit=1G /usr/local/bin/composer install --prefer-dist -n
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --extensions=php --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - travis_retry php vendor/bin/coveralls
